const quotes = ["\"Might want to train your wife how to play your account. Idk if we want to lose any more top players.\" - Sharpie, when we thought Rob might die from the vaccine.",
    "\"He just won't stop.\" - Bollo.", "\"Huge!!\" - Trashpanda.",
    "\"I'm not a dickmaster or am I? :thinking:\" - ksgro.", "\"Trashpanda fuck dude that was long.\" - ThePolishPowerhouse.",
    "\"Damn chilenos up our rear.\" - Rob.", "\"Send nudes.\" - r3NICKulous all the time.", "\"I see the whales are at it again :whale:\" - John Murphy on facebook, all the time.",
    "\"I don't mind spending a little extra time on the toilet the next day. More SPPD time.\" - Sharpie.", "\"Not sure why Rob is talking. His average is only 113.6 #notimpressed. Lol\" - Sharpie.",
    "\"The media will always blow things up to scare people. That's how I'm looking at it. If you check facts the flu has killed and affected more people.\" - ksgro on COVID.",
    "\"Sheriff is the play.\" - Trashpanda, always.", "\"I work hard outside this game, I'm on discord everyday, team chats everyday, recruiting and even making videos to push my team AND my own personal growth.\" - Mikey.",
    "\"Making onlyfans videos to help his team grow.\" - Rob, about Mikey lol.", "\"Here in Mr. Jefferson we take SEND NUDES literally. Why are you spending your time elsewhere?\" - Underptaker, recruiting.",
    "\"I just flipping you shit.\" - Underptaker.", "\"Being a part of THIS singular non branded entity with you jackasses is what makes the game. Fuck the other teams :joy:\" - Underptaker.",
    "\"Did you win?\" - Everyone in Mr Jefferson, even after an image shows a defeat :face_with_raised_eyebrow:", "\"Maybe. But I still like her :heart:\" - Bollo, talking about Liane.",
    "\"Never thought it would come to this...\" - Bollo requesting Mimsy because of teamwars.", "\"Pretty sure you can just roll your forehead over your phone and still win games with a high level Sizzler.\" - Bollo, bitching about Sizzler.",
    "- Bollo: \"Do we need more caps math? I'm kinda dying here so if it's all good I'm going to bed :sleeping:\" \n- ROB: \"We are not paying you to sleep.\"",
    "- Sharpie: \"If it kills me, my wife will become a millionaire from my life insurance. So...fuck it.\" \n- Bollo: \"Don't forget to give your wife your account so she can whale massively with that insurance :eyes:\"",
    "- ToPoT: \"I don't know about all you guys but I sure was tired of being forced to play with myself.\" \n- Bollo: \"Nothing wrong about playing with yourself every now and then.\"",
    "\"They were good matches too. Had me puckering my butthole.\" - ksgro.", "\"I drone my baby to where he needs to go.\" - ROB.", "\"Because a experienced Chef can walk to a table and see some ingredients and go \"Oh That's stuff for an apple pie.... People who study these shots can do the same thing.... they can look at the ingredients and go.... \"Oh.! That's Mad Cow\".....\nBro , it's got a dead AIDS baby in it from 1972....... eeeeeeehhh... and jellyfish DNA.... eeehhh...\" - SuperMooching.",
    "\"Those who seek safety shall perish , but those who live for me shall find salvation..... Jesus Christ\" - SuperMooChing.", "\"My thought is that this world is over crowded and the virus is just killing off the weak people. Who cares.\" - Nirvleach :eyes:",
    "\"Rose had enough space on that driftwood for jack. No doubt.\" - ROB.", "- Sharpie: \"This is some of the dumbest shit I've seen\". \n- SuperMooching: \".....Just wait....\" \n- Nirvleach: \"Does it get dumber?\" \n- SuperMooching: \"By far... No one has been called a Nazi yet...\"",
    "\"Sharpies have no gender......as far as I know......\" - SuperMooching.", "\"I used to work with a deaf guy and I used to do the john cena thing to him but over my ears\" - r3NICKulous.",
    "- lumberjaxx: \"I'm actually really into my girlfriend. Objectifying celebrities is bad.\" \n- r3NICKulous: \"Yeah bro my wife and nirvs mom are the only women for me.\"",
    "- Sharpie: \"My wife said there will be a frasier reboot if anyone is into that.\" \n- Nirvleach: \"I'm into your wife, yes.\" \n- ROB: \"Is this the queue for Sharpie's wife?\"",
    "\"My sources tell me sticking a fork in your outlet makes the body immune to COVID. SuperMooChing give it a shot and let us know.\" - Osamas Camel.", "\"I once burped and farted at the same time. So I got that going for me.\" - ongo gablogian.",
    "\"I did the monkey and it worked pretty good.\" - ToPoT.", "\"Did you know I visited Cuba?\" - Nirvleach, every now and then.", "- ROB: \"Cuban meat always delivers.\" \n- ksgro: \"Yeah, you cubans know what's up.\"",
    "\"I think you need to be braindead to not be at 9.5k+ with a level 6 Sizzler.\" - Bollo, bitching about Sizzler again.", "\"I like the abuse apparently.\" - ksgro.", "\"I like blowing all the animals.\" - ToPoT.",
    "- ToPoT: \"Who's dick I gotta suck to get some motherfuckin PvP tickets in these lockers.\" \n- r3NICKulous: \"You can start with mine, I'll message toller after and see what I can do.\"",
    "\"I didn't even practice and got 114...ignore those friendly fights I had with Nirvleach and ROB. They needed it, not me.\" - Sharpie.",
    "\"Small penises need BJs too.\" - Trashpanda."]


module.exports = { quotes };

